### PR TITLE
Added the ability to import this program into other Python programs

### PR DESCRIPTION
**Pull request by truethari**
_I closed the [previous pull request](https://github.com/victordomingos/optimize-images/pull/32) because optimizer better than worker (function name)_

### options
```txt
src_path, watch_dir, recursive, quality, remove_transparency, reduce_colors, max_colors, max_w, max_h, keep_exif, convert_all, conv_big, force_del, bg_color, grayscale, ignore_size_comparison, fast_mode, jobs
```

### example 1
```python
from optimize_images  import optimizer
optimizer("path/to/folder", quality=40)
```

### example 2
```python
from optimize_images  import optimizer
optimizer("path/to/image", max_w=1000, max_h=700)
```

---

I changed the order of the returning values of **'get_args'** _(in argument_parser.py)_ so that the **'get_args()'** _(in main.py)_ return values were coded to be tuple type to the 'args' variable. It is now easier to call **'worker'** function without changing the order of values.

---

Changed init.py and now user can import **'worker'** without mentioning like this.
```python
from optimize_images.api  import optimizer
```
after changed the init.py
```python
from optimize_images  import optimizer
```

### CODE REVIEW

**Comment by victordomingos** [comment]
Hi! Thanks for caring about Optimize Images and for your PR. I really think it is a good idea to offer an API for developers. I have been playing myself with the idea after starting a side project called [Optimize Images X](https://github.com/victordomingos/optimize-images-x) which is based in the original Optimize Images.

I really wanted to merge your PR, but unfortunately it failed to pass my most basic test (I hope it can be fixed). I cloned your repo and created a virtual environment using `python3.9 -m venv venv`. Then I activated the virtual environment and tried to install with `python3.9 -m pip install -e .`. I get then this error message:

```
python3.9 -m pip install -e .
Obtaining file:///Users/victor/dev/pr-optimize/optimize-images
ERROR: No .egg-info directory found in /private/var/folders/xf/39kpd2dj5697yc5rc35v7xgc0000gn/T/pip-pip-egg-info-khgjwmum
```

I am not sure what is causing this issue, however I can tell this exact sequence of commands is working ok with my current repo, I have just checked. Can you please check if there's something to be fixed with regards to this?

**Comment by truethari** [comment]
OK. I will resolve this issue as soon as possible

**Comment by truethari** [comment]
That problem caused because the `setuptools` looked for imported modules in the `__init__.py` when packaging the program. When the file `__main__` is imported, setuptools will search for that file. If no dependencies are installed to venv / env, it crashes the process.

Example: _if not installed `piexif` , the process will stop there. (`main.py` line 44)_

### Fixes:
Created `api.py` and linked it to the `__init__` file.
Imported the `__main__` inside the `api.optimizer` function.

---

Setup.py was updated because the program may crash after installation if the required packages are not installed

**Comment by victordomingos** [comment]
I have merged this PR. I have noticed that for Optimize Images to be used as a package from which you can simply call a few methods it needs some improvement. For instance, if you pass an invalid path, the host application will simply exit. Which means we should be raising an exception instead of exiting and in Optimize Images - the CLI app - catch that exception. This way, other applications calling this methods could catch the application and keep running.

**Pull request merged**
