### PR TITLE
skip unsupported formats

### PR DESCRIPTION
**Pull request by liashchynskyi**
**skip unsupported formats**

### CODE REVIEW

**Comment by liashchynskyi** [comment]
@victordomingos I have tested it out. It works. But I'm not sure about *JPG*. In the docs I found only *JPEG*. I suppose it uses format of the file, not extension. I'll try it tomorrow and let you know.

https://pillow.readthedocs.io/en/5.2.x/reference/Image.html#PIL.Image.format

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html

**Comment by victordomingos** [comment]
I believe “JPEG” should be the only valid format descriptor in this case, judging from Pillow’s documentation.

**Comment by liashchynskyi** [comment]
@victordomingos fixed

**Comment by victordomingos** [comment]
Thanks for your contribution.

**Pull request merged**
